: ${NAO_NAME:=nao}
: ${NAO_TYPE:=nao}
: ${NAO_RAPP_PACKAGE_WHITELIST:=[rocon_apps]}
: ${NAO_RAPP_PACKAGE_BLACKLIST:=[]}
: ${NAO_INTERACTIONS_LIST:=[]}


export NAO_NAME
export NAO_TYPE
export NAO_RAPP_PACKAGE_WHITELIST 
export NAO_RAPP_PACKAGE_BLACKLIST
export NAO_INTERACTIONS_LIST
